package common;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public class FacilityTypes {
    public static Map<String, List<String>> dictionary;

    static {
        dictionary = new TreeMap<>();

        List<String> biofuelsTypes = new ArrayList<>();
        List<String> coalTypes = new ArrayList<>();
        List<String> communicationsTypes = new ArrayList<>();
        List<String> electricityTypes = new ArrayList<>();
        List<String> generalFacilitiesTypes = new ArrayList<>();
        List<String> healthcareTypes = new ArrayList<>();
        List<String> manufacturingTypes = new ArrayList<>();
        List<String> naturalGasTypes = new ArrayList<>();
        List<String> petroleumTypes = new ArrayList<>();
        List<String> waterTypes = new ArrayList<>();
        List<String> wastewaterSystemTypes = new ArrayList<>();
        List<String> recycledWaterSystemTypes = new ArrayList<>();

        biofuelsTypes.add("Biodiesel_Production_Plant");
        biofuelsTypes.add("Ethanol_Production_Plant");
        coalTypes.add("Coal_Cleaning_Plant");
        coalTypes.add("Coal_Mine");
        coalTypes.add("Coal_Preparation_Plant");
        coalTypes.add("Coal_Pulverizing_Plant");
        coalTypes.add("Coal_Surface_Mine");
        coalTypes.add("Coal_Underground_Mine");
        communicationsTypes.add("AM_Radio");
        communicationsTypes.add("Access_Tandem");
        communicationsTypes.add("Cable_Television_Network");
        communicationsTypes.add("Cellular_Site");
        communicationsTypes.add("Central_Office");
        communicationsTypes.add("Coaxial_Cable");
        communicationsTypes.add("Copper_Pair");
        communicationsTypes.add("Data_Center");
        communicationsTypes.add("Digital_Television_Radio");
        communicationsTypes.add("FM_Radio");
        communicationsTypes.add("Headend_Facility");
        communicationsTypes.add("Interconnection_Facility_(Internet)");
        communicationsTypes.add("Internet_Exchange_Point");
        communicationsTypes.add("Local_Area_Network");
        communicationsTypes.add("Microwave_Site");
        communicationsTypes.add("Mobile_Telephone_Switching_Office");
        communicationsTypes.add("Network");
        communicationsTypes.add("Network_Access_Point");
        communicationsTypes.add("Network_Operations_Center");
        communicationsTypes.add("Optical_Fiber");
        communicationsTypes.add("Peering_Point");
        communicationsTypes.add("Point_of_Presence");
        communicationsTypes.add("Radio_Broadcast_Site");
        communicationsTypes.add("Radio_Systems");
        communicationsTypes.add("SCADA_Network");
        communicationsTypes.add("Satellite_Ground_Station");
        communicationsTypes.add("Submarine_Cable");
        communicationsTypes.add("Switching/Routing_Facility");
        communicationsTypes.add("Telephone_Switching_Facility");
        communicationsTypes.add("Toll_Office");
        communicationsTypes.add("Wide_Area_Network");
        communicationsTypes.add("Wired_Link");
        electricityTypes.add("Battery");
        electricityTypes.add("Capacitor_Station");
        electricityTypes.add("Circuit_(Line)");
        electricityTypes.add("Coal_Fired_Generation_Plant");
        electricityTypes.add("Combined_Heat_Power_Plant");
        electricityTypes.add("Compressed_Air");
        electricityTypes.add("Concentrated_Solar");
        electricityTypes.add("Direct_Current_Converter_Station");
        electricityTypes.add("Dispatch_and_Control_Center");
        electricityTypes.add("Distillate_Fuel_Oil_Generation_Plant");
        electricityTypes.add("Energy_Storage");
        electricityTypes.add("Flywheel");
        electricityTypes.add("Fossil_Fuel_Generation_Plant");
        electricityTypes.add("Fuel_Cell");
        electricityTypes.add("Generation_Plant");
        electricityTypes.add("Geothermal_Generation_Plant");
        electricityTypes.add("Hydroelectric_Facility");
        electricityTypes.add("Natural_Gas_Generation_Plant");
        electricityTypes.add("Nuclear_Generation_Plant");
        electricityTypes.add("Photovoltaic");
        electricityTypes.add("Renewable_Generation_Plant");
        electricityTypes.add("Solar_Generation_Facility");
        electricityTypes.add("Substation");
        electricityTypes.add("Transmission_and_Distribution");
        electricityTypes.add("Wind_Farm");
        electricityTypes.add("Wind_Turbine");
        generalFacilitiesTypes.add("Campus_(Installation)");
        generalFacilitiesTypes.add("Office_Building");
        healthcareTypes.add("Blood_Manufacturing_Facility");
        healthcareTypes.add("Hospital");
        healthcareTypes.add("Linens");
        healthcareTypes.add("Medical_Laboratory");
        healthcareTypes.add("Support_Service");
        manufacturingTypes.add("Nuclear_Fuel_Fabrication");
        manufacturingTypes.add("Olefin_Plant");
        manufacturingTypes.add("Petrochemical_Manufacturing");
        manufacturingTypes.add("Plastic_Product_Manufacturing");
        naturalGasTypes.add("Compressed_Natural_Gas_Plant");
        naturalGasTypes.add("Condensate_Storage_Tank");
        naturalGasTypes.add("Dehydrator");
        naturalGasTypes.add("Dispatch_and_Control_Center");
        naturalGasTypes.add("Liquefied_Natural_Gas_Plant");
        naturalGasTypes.add("Local_Distribution_System");
        naturalGasTypes.add("Natural_Gas_Compressor_Station");
        naturalGasTypes.add("Natural_Gas_Gathering_Pipeline");
        naturalGasTypes.add("Natural_Gas_Liquids_Fractionation_Plant");
        naturalGasTypes.add("Natural_Gas_Liquids_Pipeline");
        naturalGasTypes.add("Natural_Gas_Liquids_Storage_Facility");
        naturalGasTypes.add("Natural_Gas_Market_Hub");
        naturalGasTypes.add("Natural_Gas_Metering_Station");
        naturalGasTypes.add("Natural_Gas_Processing_Plant");
        naturalGasTypes.add("Natural_Gas_Storage_Facility");
        naturalGasTypes.add("Natural_Gas_Transmission_Pipeline");
        naturalGasTypes.add("Production_Separator");
        naturalGasTypes.add("Production_Wellhead");
        naturalGasTypes.add("Regulator_Station");
        petroleumTypes.add("Carbon_Dioxide_Pipeline");
        petroleumTypes.add("Crude_Oil");
        petroleumTypes.add("Crude_Oil_Feeder_Pipeline");
        petroleumTypes.add("Crude_Oil_Gathering_Pipeline");
        petroleumTypes.add("Crude_Oil_Tank");
        petroleumTypes.add("Crude_Oil_Transmission_Pipeline");
        petroleumTypes.add("Dispatch_and_Control_Center");
        petroleumTypes.add("Heater-Treater");
        petroleumTypes.add("Highly_Volatile_Liquid_Pipeline_");
        petroleumTypes.add("Line_Heater");
        petroleumTypes.add("Petroleum_Bulk_Terminal");
        petroleumTypes.add("Petroleum_Product");
        petroleumTypes.add("Petroleum_Pump_Station");
        petroleumTypes.add("Production_Wellhead");
        petroleumTypes.add("Refined_Product_Pipeline");
        petroleumTypes.add("Refinery");
        recycledWaterSystemTypes.add("Recycled_Water_Pump_Station");
        recycledWaterSystemTypes.add("Recycled_Water_Reservior");
        recycledWaterSystemTypes.add("Recycled_Water_Storage");
        recycledWaterSystemTypes.add("Recycled_Water_System");
        recycledWaterSystemTypes.add("Recycled_Water_Tank");
        recycledWaterSystemTypes.add("Recycled_Water_Treatment_Plant");
        wastewaterSystemTypes.add("Wastewater_Force_Main");
        wastewaterSystemTypes.add("Wastewater_Gravity_Main");
        wastewaterSystemTypes.add("Wastewater_Lift_Station");
        wastewaterSystemTypes.add("Wastewater_Pump_Station");
        wastewaterSystemTypes.add("Wastewater_System");
        wastewaterSystemTypes.add("Wastewater_Treatment_Plant");
        waterTypes.add("Aquifer_Storage_Recovery");
        waterTypes.add("Combined_Sewer_Outfall");
        waterTypes.add("Diversion_Dam");
        waterTypes.add("Finished_Water_Main");
        waterTypes.add("Finished_Water_Pump_Station");
        waterTypes.add("Finished_Water_Reservior");
        waterTypes.add("Finished_Water_Storage");
        waterTypes.add("Finished_Water_System");
        waterTypes.add("Finished_Water_Tower");
        waterTypes.add("Ground_Water_Well");
        waterTypes.add("Interconnect");
        waterTypes.add("Raw_Water_Aqueduct");
        waterTypes.add("Raw_Water_Canal");
        waterTypes.add("Raw_Water_Conveyance");
        waterTypes.add("Raw_Water_Intake");
        waterTypes.add("Raw_Water_Pipeline");
        waterTypes.add("Raw_Water_Pump_Station");
        waterTypes.add("Raw_Water_Reservior");
        waterTypes.add("Raw_Water_Storage");
        waterTypes.add("Raw_Water_System");
        waterTypes.add("Raw_Water_Tank");
        waterTypes.add("Water_System_Control_Center");
        waterTypes.add("Water_Treatment_Plant");


        dictionary.put("Biofuels", biofuelsTypes);
        dictionary.put("Coal", coalTypes);
        dictionary.put("Communications", communicationsTypes);
        dictionary.put("Electricity", electricityTypes);
        dictionary.put("General_Facilities", generalFacilitiesTypes);
        dictionary.put("Healthcare", healthcareTypes);
        dictionary.put("Manufacturing", manufacturingTypes);
        dictionary.put("Natural_Gas", naturalGasTypes);
        dictionary.put("Petroleum", petroleumTypes);
        dictionary.put("Recycled_Water_System", recycledWaterSystemTypes);
        dictionary.put("Wastewater_System", wastewaterSystemTypes);
        dictionary.put("Water", waterTypes);
    }
}
